export const CRYPTO_RECONCILIATION_TYPES = [
  'UNDERPAID',
  'OVERPAID',
  'ASSET_MISMATCH',
  'AMOUNT_UNDETERMINED',
  'PAYMENT_AFTER_EXPIRY',
  'PAYMENT_ON_TERMINAL_INTENT',
  'UNKNOWN_PROVIDER_REFERENCE',
  'FINANCIAL_INSTRUCTION_MISSING',
  'INTENT_EXPIRED_AFTER_PAYMENT_DETECTED',
] as const

export type CryptoReconciliationType = (typeof CRYPTO_RECONCILIATION_TYPES)[number]
