export const KYC_REASON_CODES = [
  'KYC_SESSION_STARTED',
  'KYC_PROVIDER_VERIFIED',
  'KYC_PROVIDER_FAILED',
  'KYC_PROVIDER_MANUAL_REVIEW',
  'KYC_SESSION_EXPIRED',
  'KYC_VERIFICATION_EXPIRED',
  'KYC_EVENT_DUPLICATE',
  'KYC_EVENT_STALE',
  'KYC_EVENT_INVALID',
  'KYC_PROVIDER_REFERENCE_MISMATCH',
  'KYC_TRANSITION_NOT_ALLOWED',
  'KYC_PROFILE_CREATED',
] as const

export type KycReasonCode = (typeof KYC_REASON_CODES)[number]
