export const ELIGIBILITY_REASON_CODES = [
  'ACCOUNT_RESTRICTED',
  'ACCOUNT_SUSPENDED',
  'ACCOUNT_CLOSED',
  'KYC_NOT_VERIFIED',
  'KYC_PENDING',
  'SECURITY_REVIEW',
  'SELF_EXCLUDED',
  'JURISDICTION_BLOCKED',
  'WAGERING_BLOCKED',
  'DEPOSITS_BLOCKED',
  'WITHDRAWALS_BLOCKED',
  'POLICY_DATA_INCOMPLETE',
] as const

export type EligibilityReasonCode = (typeof ELIGIBILITY_REASON_CODES)[number]
